app:
  name: ns-svg-converter-app

spring:
  profiles:
    active: dao_memory

server:
  port: ${PORT:8080}
  ssl:
    enabled: false
    keyStoreType: PKCS12
    key-store: ${KEYSTORE_PATH:./ns-main-service/build/keystore.jks}
    key-store-password: pleasedonotuse
    keyAlias: svg-converter

cassandra:
  host: localhost
  port: 9042
  keyspace: ns_svg_main
  dataCenter: DC1
  replicateFactor: 1

logging:
  level:
    ROOT: INFO
